### ISSUE TITLE
Attack plan --> Directory listing

### ISSUE THREAD

**Issue by jaumellb** [AngelMascaro/prioritask---G1-Old-school---Engagement-Auditoria#6]
Persona --> Jaume
Temps --> 06/03/2023 --> 19:15 --> 19:25
Acció --> Directory listing
Endpoint --> 192.168.255.26
Resultat --> S'han trobat les rutes `css` i  a `js` on hi ha el + Indexes activat.
Output:

![image](https://user-images.githubusercontent.com/113126548/223199061-504496f3-9037-4b08-a93d-02200c36f5c7.png)

![image](https://user-images.githubusercontent.com/113126548/223198967-e2b54034-fdbd-4431-8177-a8945f97b03d.png)

**Comment by AngelMascaro** [comment]
Persona --> Angel
Temps --> 08/03/2023 --> 11:15 --> 11:30
Acció --> Reconeixement actiu amb OWASP ZAP
Endpoint --> 192.168.255.26
Resultat --> Informe generat amb owasz zap
Output:-->
![zap1](https://user-images.githubusercontent.com/78735128/223796270-26277838-e717-4211-a78e-f785f4f0da6e.png)
![zap2](https://user-images.githubusercontent.com/78735128/223796299-c4bfa188-05ed-4e0b-abf1-d67304458f3a.png)
![zap3](https://user-images.githubusercontent.com/78735128/223796315-b4acd36d-3360-4d2b-bdc6-7919bdc13b14.png)
![zap4](https://user-images.githubusercontent.com/78735128/223796333-d8586c0a-8e9a-4543-90eb-897cd902a198.png)
![zap5](https://user-images.githubusercontent.com/78735128/223796355-7e5bcb1e-ba0b-4820-8d79-435c372a4769.png)
![zap6](https://user-images.githubusercontent.com/78735128/223796360-6902b4b6-69e1-49ba-8788-518be4dea093.png)
![zap7](https://user-images.githubusercontent.com/78735128/223796375-b01e9768-6b43-40c2-b422-99b44abee4d8.png)
![zap8](https://user-images.githubusercontent.com/78735128/223796382-d247db4c-56b5-41d0-a999-f7ffe63f6698.png)
